<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.techsenger.ceffx</groupId>
        <artifactId>ceffx</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>com.techsenger.ceffx</groupId>
    <artifactId>ceffx-natives</artifactId>
    <packaging>jar</packaging>
    <name>CEFFX - Natives</name>
    <description>Native libraries module</description>

    <profiles>
        <profile>
            <id>linux</id>
            <activation>
                <os>
                    <name>Linux</name>
                </os>
            </activation>
            <properties>
                <natives.classifier>linux</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <name>Mac OS X</name>
                    <arch>x86_64</arch>
                </os>
            </activation>
            <properties>
                <natives.classifier>mac</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>mac-aarch64</id>
            <activation>
                <os>
                    <name>Mac OS X</name>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <properties>
                <natives.classifier>mac-aarch64</natives.classifier>
            </properties>
        </profile>
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <natives.classifier>win</natives.classifier>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
        <plugin>
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
                <includes>
                    <!-- The JAR without a classifier contains no code -->
                    <include>__nothing__/**</include>
                </includes>
            </configuration>
        </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-native-libs</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/native/libs</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/../native/build/src/Release</directory>
                                    <includes>
                                        <include>libceffx.so</include>
                                        <include>libceffx.dylib</include>
                                        <include>ceffx.dll</include>
                                        <include>ceffx_helper</include>
                                        <include>ceffx_helper.exe</include>
                                        <include>ceffx Helper.app/**</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>native-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/assembly/native.xml</descriptor>
                            </descriptors>
                            <finalName>${project.artifactId}-${project.version}</finalName>
                            <appendAssemblyId>true</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>