/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_CefApp */

#ifndef _Included_com_techsenger_ceffx_core_CefApp
#define _Included_com_techsenger_ceffx_core_CefApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_Startup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1Startup(JNIEnv*,
                                                          jclass,
                                                          jstring);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_PreInitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1PreInitialize(JNIEnv*,
                                                                jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_Initialize
 * Signature: (Lcom/techsenger/ceffx/core/handler/CefAppHandler;Lcom/techsenger/ceffx/core/CefSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1Initialize(JNIEnv*,
                                                             jobject,
                                                             jobject,
                                                             jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1Shutdown(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_DoMessageLoopWork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1DoMessageLoopWork(JNIEnv*,
                                                                jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_GetVersion
 * Signature: ()Lcom/techsenger/ceffx/core/CefApp/CefVersion;
 */
JNIEXPORT jobject JNICALL Java_com_techsenger_ceffx_core_CefApp_N_1GetVersion(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_RegisterSchemeHandlerFactory
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Lcom/techsenger/ceffx/core/callback/CefSchemeHandlerFactory;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_CefApp_N_1RegisterSchemeHandlerFactory(JNIEnv*,
                                                    jobject,
                                                    jstring,
                                                    jstring,
                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_CefApp
 * Method:    N_ClearSchemeHandlerFactories
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_CefApp_N_1ClearSchemeHandlerFactories(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_techsenger_ceffx_core_CefApp_CefAppState */

#ifndef _Included_com_techsenger_ceffx_core_CefApp_CefAppState
#define _Included_com_techsenger_ceffx_core_CefApp_CefAppState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_techsenger_ceffx_core_CefApp_CefVersion */

#ifndef _Included_com_techsenger_ceffx_core_CefApp_CefVersion
#define _Included_com_techsenger_ceffx_core_CefApp_CefVersion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
