/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_browser_CefBrowser_N */

#ifndef _Included_com_techsenger_ceffx_core_browser_CefBrowser_N
#define _Included_com_techsenger_ceffx_core_browser_CefBrowser_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_CreateBrowser
 * Signature:
 * (Lcom/techsenger/ceffx/core/handler/CefClientHandler;JLjava/lang/String;ZZLcom/techsenger/ceffx/core/browser/CefRequestContext;Lcom/techsenger/ceffx/core/CefBrowserSettings;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1CreateBrowser(JNIEnv*,
                                                    jobject,
                                                    jobject,
                                                    jlong,
                                                    jstring,
                                                    jboolean,
                                                    jboolean,
                                                    jobject,
                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_CreateDevTools
 * Signature:
 * (Lcom/techsenger/ceffx/core/browser/CefBrowser;Lcom/techsenger/ceffx/core/handler/CefClientHandler;JZZLjavafx/geometry/Point2D;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1CreateDevTools(JNIEnv*,
                                                     jobject,
                                                     jobject,
                                                     jobject,
                                                     jlong,
                                                     jboolean,
                                                     jboolean,
                                                     jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_ExecuteDevToolsMethod
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Lcom/techsenger/ceffx/core/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1ExecuteDevToolsMethod(JNIEnv*,
                                                            jobject,
                                                            jstring,
                                                            jstring,
                                                            jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_AddDevToolsMessageObserver
 * Signature:
 * (Lcom/techsenger/ceffx/core/browser/CefDevToolsMessageObserver;)Lcom/techsenger/ceffx/core/browser/CefRegistration;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1AddDevToolsMessageObserver(JNIEnv*,
                                                                 jobject,
                                                                 jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetWindowHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetWindowHandle(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_CanGoBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1CanGoBack(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GoBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GoBack(JNIEnv*,
                                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_CanGoForward
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1CanGoForward(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GoForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GoForward(JNIEnv*,
                                                                       jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_IsLoading
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1IsLoading(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_Reload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1Reload(JNIEnv*,
                                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_ReloadIgnoreCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1ReloadIgnoreCache(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_StopLoad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1StopLoad(JNIEnv*,
                                                                      jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetIdentifier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetIdentifier(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetMainFrame
 * Signature: ()Lcom/techsenger/ceffx/core/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetMainFrame(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFocusedFrame
 * Signature: ()Lcom/techsenger/ceffx/core/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFocusedFrame(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFrameByIdentifier
 * Signature: (Ljava/lang/String;)Lcom/techsenger/ceffx/core/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFrameByIdentifier(JNIEnv*,
                                                           jobject,
                                                           jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFrameByName
 * Signature: (Ljava/lang/String;)Lcom/techsenger/ceffx/core/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFrameByName(JNIEnv*, jobject, jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFrameIdentifiers
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFrameIdentifiers(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFrameNames
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFrameNames(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetFrameCount(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_IsPopup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1IsPopup(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_HasDocument
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1HasDocument(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_ViewSource
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1ViewSource(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetSource
 * Signature: (Lcom/techsenger/ceffx/core/callback/CefStringVisitor;)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetSource(JNIEnv*,
                                                                       jobject,
                                                                       jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetText
 * Signature: (Lcom/techsenger/ceffx/core/callback/CefStringVisitor;)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetText(JNIEnv*,
                                                                     jobject,
                                                                     jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_LoadRequest
 * Signature: (Lcom/techsenger/ceffx/core/network/CefRequest;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1LoadRequest(JNIEnv*, jobject, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_LoadURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1LoadURL(JNIEnv*,
                                                                     jobject,
                                                                     jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_ExecuteJavaScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1ExecuteJavaScript(JNIEnv*,
                                                        jobject,
                                                        jstring,
                                                        jstring,
                                                        jint);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetURL(JNIEnv*,
                                                                       jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_Close
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1Close(JNIEnv*,
                                                                   jobject,
                                                                   jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SetFocus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SetFocus(JNIEnv*,
                                                                      jobject,
                                                                      jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SetWindowVisibility
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SetWindowVisibility(JNIEnv*,
                                                          jobject,
                                                          jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetZoomLevel
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetZoomLevel(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SetZoomLevel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SetZoomLevel(JNIEnv*, jobject, jdouble);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_RunFileDialog
 * Signature:
 * (Lcom/techsenger/ceffx/core/handler/CefDialogHandler/FileDialogMode;Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;ILcom/techsenger/ceffx/core/callback/CefRunFileDialogCallback;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1RunFileDialog(JNIEnv*,
                                                    jobject,
                                                    jobject,
                                                    jstring,
                                                    jstring,
                                                    jobject,
                                                    jint,
                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_StartDownload
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1StartDownload(JNIEnv*, jobject, jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1Print(JNIEnv*,
                                                                   jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_PrintToPDF
 * Signature:
 * (Ljava/lang/String;Lcom/techsenger/ceffx/core/misc/CefPdfPrintSettings;Lcom/techsenger/ceffx/core/callback/CefPdfPrintCallback;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1PrintToPDF(JNIEnv*,
                                                 jobject,
                                                 jstring,
                                                 jobject,
                                                 jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_Find
 * Signature: (Ljava/lang/String;ZZZ)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1Find(JNIEnv*,
                                                                  jobject,
                                                                  jstring,
                                                                  jboolean,
                                                                  jboolean,
                                                                  jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_StopFinding
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1StopFinding(JNIEnv*, jobject, jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_CloseDevTools
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1CloseDevTools(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_ReplaceMisspelling
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1ReplaceMisspelling(JNIEnv*,
                                                         jobject,
                                                         jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_WasResized
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1WasResized(JNIEnv*,
                                                                        jobject,
                                                                        jint,
                                                                        jint);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_Invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1Invalidate(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SendKeyEvent
 * Signature: (Ljavafx/scene/input/KeyEvent;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SendKeyEvent(JNIEnv*, jobject, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SendMouseEvent
 * Signature: (Ljavafx/scene/input/MouseEvent;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SendMouseEvent(JNIEnv*, jobject, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SendMouseWheelEvent
 * Signature: (Ljavafx/scene/input/ScrollEvent;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SendMouseWheelEvent(JNIEnv*,
                                                          jobject,
                                                          jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragTargetDragEnter
 * Signature: (Lcom/techsenger/ceffx/core/callback/CefDragData;Ljavafx/geometry/Point2D;II)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragTargetDragEnter(
                                                        JNIEnv* env,
                                                        jobject obj,
                                                        jobject jdragData,
                                                        jobject jpoint,
                                                        jint modifiers,
                                                        jint allowedOps);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragTargetDragOver
 * Signature: (Ljavafx/geometry/Point2D;II)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragTargetDragOver(
                                                        JNIEnv* env,
                                                        jobject obj,
                                                        jobject jpoint,
                                                        jint jmodifiers,
                                                        jint allowedOps);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragTargetDragLeave
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragTargetDragLeave(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragTargetDrop
 * Signature: (Ljavafx/geometry/Point2D;I)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragTargetDrop(
                                                    JNIEnv* env,
                                                    jobject obj,
                                                    jobject jpoint,
                                                    jint jmodifiers);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragSourceEndedAt
 * Signature: (Ljavafx/geometry/Point2D;I)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragSourceEndedAt(
                                                JNIEnv* env,
                                                jobject obj,
                                                jobject jpoint,
                                                jint jmodifiers);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_DragSourceSystemDragEnded
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1DragSourceSystemDragEnded(JNIEnv*,
                                                                jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_UpdateUI
 * Signature: (Ljavafx/geometry/BoundingBox;Ljavafx/geometry/BoundingBox;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1UpdateUI(
                                                                JNIEnv*,
                                                                jobject,
                                                                jobject,
                                                                jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SetParent
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SetParent(JNIEnv*,
                                                                 jobject,
                                                                 jlong,
                                                                 jlong);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_NotifyMoveOrResizeStarted
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1NotifyMoveOrResizeStarted(JNIEnv*,
                                                                jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_SetWindowlessFrameRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1SetWindowlessFrameRate(JNIEnv*,
                                                             jobject,
                                                             jint);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefBrowser_N
 * Method:    N_GetWindowlessFrameRate
 * Signature: (Lcom/techsenger/ceffx/core/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefBrowser_1N_N_1GetWindowlessFrameRate(JNIEnv*,
                                                             jobject,
                                                             jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_techsenger_ceffx_core_browser_CefBrowser_N_IntCallback */

#ifndef _Included_com_techsenger_ceffx_core_browser_CefBrowser_N_IntCallback
#define _Included_com_techsenger_ceffx_core_browser_CefBrowser_N_IntCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
