/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_network_CefCookieManager_N */

#ifndef _Included_com_techsenger_ceffx_core_network_CefCookieManager_N
#define _Included_com_techsenger_ceffx_core_network_CefCookieManager_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_GetGlobalManager
 * Signature: ()Lcom/techsenger/ceffx/core/network/CefCookieManager_N;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1GetGlobalManager(JNIEnv*, jclass);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1Dispose(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_VisitAllCookies
 * Signature: (JLcom/techsenger/ceffx/core/callback/CefCookieVisitor;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1VisitAllCookies(JNIEnv*,
                                                            jobject,
                                                            jlong,
                                                            jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_VisitUrlCookies
 * Signature: (JLjava/lang/String;ZLcom/techsenger/ceffx/core/callback/CefCookieVisitor;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1VisitUrlCookies(JNIEnv*,
                                                            jobject,
                                                            jlong,
                                                            jstring,
                                                            jboolean,
                                                            jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_SetCookie
 * Signature: (JLjava/lang/String;Lcom/techsenger/ceffx/core/network/CefCookie;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1SetCookie(JNIEnv*,
                                                      jobject,
                                                      jlong,
                                                      jstring,
                                                      jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_DeleteCookies
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1DeleteCookies(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jstring,
                                                          jstring);

/*
 * Class:     com_techsenger_ceffx_core_network_CefCookieManager_N
 * Method:    N_FlushStore
 * Signature: (JLcom/techsenger/ceffx/core/callback/CefCompletionCallback;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefCookieManager_1N_N_1FlushStore(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject);

#ifdef __cplusplus
}
#endif
#endif
