/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N */

#ifndef _Included_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
#define _Included_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_1N_N_1Dispose(JNIEnv*,
                                                            jobject,
                                                            jlong);

/*
 * Class:     com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
 * Method:    N_Cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_1N_N_1Cancel(JNIEnv*,
                                                           jobject,
                                                           jlong);

/*
 * Class:     com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
 * Method:    N_Pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_1N_N_1Pause(JNIEnv*,
                                                          jobject,
                                                          jlong);

/*
 * Class:     com_techsenger_ceffx_core_callback_CefDownloadItemCallback_N
 * Method:    N_Resume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefDownloadItemCallback_1N_N_1Resume(JNIEnv*,
                                                           jobject,
                                                           jlong);

#ifdef __cplusplus
}
#endif
#endif
