/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_callback_CefFileDialogCallback_N */

#ifndef _Included_com_techsenger_ceffx_core_callback_CefFileDialogCallback_N
#define _Included_com_techsenger_ceffx_core_callback_CefFileDialogCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_callback_CefFileDialogCallback_N
 * Method:    N_Continue
 * Signature: (JLjava/util/Vector;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefFileDialogCallback_1N_N_1Continue(JNIEnv*,
                                                           jobject,
                                                           jlong,
                                                           jobject);

/*
 * Class:     com_techsenger_ceffx_core_callback_CefFileDialogCallback_N
 * Method:    N_Cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_callback_CefFileDialogCallback_1N_N_1Cancel(JNIEnv*,
                                                         jobject,
                                                         jlong);

#ifdef __cplusplus
}
#endif
#endif
