/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_browser_CefMessageRouter_N */

#ifndef _Included_com_techsenger_ceffx_core_browser_CefMessageRouter_N
#define _Included_com_techsenger_ceffx_core_browser_CefMessageRouter_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_browser_CefMessageRouter_N
 * Method:    N_Create
 * Signature:
 * (Lcom/techsenger/ceffx/core/browser/CefMessageRouter/CefMessageRouterConfig;)Lcom/techsenger/ceffx/core/browser/CefMessageRouter_N;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefMessageRouter_1N_N_1Create(JNIEnv*, jclass, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefMessageRouter_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefMessageRouter_1N_N_1Dispose(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefMessageRouter_N
 * Method:    N_AddHandler
 * Signature: (JLcom/techsenger/ceffx/core/handler/CefMessageRouterHandler;Z)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefMessageRouter_1N_N_1AddHandler(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jobject,
                                                       jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefMessageRouter_N
 * Method:    N_RemoveHandler
 * Signature: (JLcom/techsenger/ceffx/core/handler/CefMessageRouterHandler;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefMessageRouter_1N_N_1RemoveHandler(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefMessageRouter_N
 * Method:    N_CancelPending
 * Signature:
 * (JLcom/techsenger/ceffx/core/browser/CefBrowser;Lcom/techsenger/ceffx/core/handler/CefMessageRouterHandler;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefMessageRouter_1N_N_1CancelPending(JNIEnv*,
                                                          jobject,
                                                          jlong,
                                                          jobject,
                                                          jobject);

#ifdef __cplusplus
}
#endif
#endif
