/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_network_CefResponse_N */

#ifndef _Included_com_techsenger_ceffx_core_network_CefResponse_N
#define _Included_com_techsenger_ceffx_core_network_CefResponse_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_Create
 * Signature: ()Lcom/techsenger/ceffx/core/network/CefResponse_N;
 */
JNIEXPORT jobject JNICALL Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1Create(JNIEnv*,
                                                                        jclass);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1Dispose(JNIEnv*,
                                                                      jobject,
                                                                      jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_IsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1IsReadOnly(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetError
 * Signature: (J)Lcom/techsenger/ceffx/core/handler/CefLoadHandler/ErrorCode;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetError(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetError
 * Signature: (JLcom/techsenger/ceffx/core/handler/CefLoadHandler/ErrorCode;)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetError(JNIEnv*,
                                                                       jobject,
                                                                       jlong,
                                                                       jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetStatus(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetStatus
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetStatus(JNIEnv*,
                                                                        jobject,
                                                                        jlong,
                                                                        jint);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetStatusText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetStatusText(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetStatusText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetStatusText(JNIEnv*,
                                                     jobject,
                                                     jlong,
                                                     jstring);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetMimeType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetMimeType(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetMimeType
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetMimeType(JNIEnv*,
                                                   jobject,
                                                   jlong,
                                                   jstring);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetHeaderByName
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetHeaderByName(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jstring);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetHeaderByName
 * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetHeaderByName(JNIEnv*,
                                                       jobject,
                                                       jlong,
                                                       jstring,
                                                       jstring,
                                                       jboolean);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_GetHeaderMap
 * Signature: (JLjava/util/Map;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1GetHeaderMap(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefResponse_N
 * Method:    N_SetHeaderMap
 * Signature: (JLjava/util/Map;)V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_network_CefResponse_1N_N_1SetHeaderMap(JNIEnv*,
                                                    jobject,
                                                    jlong,
                                                    jobject);

#ifdef __cplusplus
}
#endif
#endif
