/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_browser_CefRequestContext_N */

#ifndef _Included_com_techsenger_ceffx_core_browser_CefRequestContext_N
#define _Included_com_techsenger_ceffx_core_browser_CefRequestContext_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_GetGlobalContext
 * Signature: ()Lcom/techsenger/ceffx/core/browser/CefRequestContext_N;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1GetGlobalContext(JNIEnv*, jclass);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_CreateContext
 * Signature:
 * (Lcom/techsenger/ceffx/core/handler/CefRequestContextHandler;)Lcom/techsenger/ceffx/core/browser/CefRequestContext_N;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1CreateContext(JNIEnv*,
                                                           jclass,
                                                           jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_IsGlobal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1IsGlobal(JNIEnv*, jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_HasPreference
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1HasPreference(JNIEnv*,
                                                           jobject,
                                                           jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_GetPreference
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1GetPreference(JNIEnv*,
                                                           jobject,
                                                           jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_GetAllPreferences
 * Signature: (Z)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1GetAllPreferences(JNIEnv*,
                                                               jobject,
                                                               jboolean);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_CanSetPreference
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1CanSetPreference(JNIEnv*,
                                                              jobject,
                                                              jstring);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_SetPreference
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Lcom/techsenger/ceffx/core;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1SetPreference(JNIEnv*,
                                                           jobject,
                                                           jstring,
                                                           jobject);

/*
 * Class:     com_techsenger_ceffx_core_browser_CefRequestContext_N
 * Method:    N_CefRequestContext_DTOR
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_techsenger_ceffx_core_browser_CefRequestContext_1N_N_1CefRequestContext_1DTOR(JNIEnv*,
                                                                     jobject);

#ifdef __cplusplus
}
#endif
#endif
