/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techsenger_ceffx_core_network_CefURLRequest_N */

#ifndef _Included_com_techsenger_ceffx_core_network_CefURLRequest_N
#define _Included_com_techsenger_ceffx_core_network_CefURLRequest_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_Create
 * Signature:
 * (Lcom/techsenger/ceffx/core/network/CefRequest;Lcom/techsenger/ceffx/core/callback/CefURLRequestClient;)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1Create(JNIEnv*,
                                                                       jobject,
                                                                       jobject,
                                                                       jobject);

/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1Dispose(JNIEnv*,
                                                                        jobject,
                                                                        jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_GetRequestStatus
 * Signature: (J)Lcom/techsenger/ceffx/core/network/CefURLRequest/Status;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1GetRequestStatus(JNIEnv*,
                                                          jobject,
                                                          jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_GetRequestError
 * Signature: (J)Lcom/techsenger/ceffx/core/handler/CefLoadHandler/ErrorCode;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1GetRequestError(JNIEnv*,
                                                         jobject,
                                                         jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_GetResponse
 * Signature: (J)Lcom/techsenger/ceffx/core/network/CefResponse;
 */
JNIEXPORT jobject JNICALL
Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1GetResponse(JNIEnv*, jobject, jlong);

/*
 * Class:     com_techsenger_ceffx_core_network_CefURLRequest_N
 * Method:    N_Cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_techsenger_ceffx_core_network_CefURLRequest_1N_N_1Cancel(JNIEnv*,
                                                                       jobject,
                                                                       jlong);

#ifdef __cplusplus
}
#endif
#endif
